I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 134, in script
    init python:
  File "game/script.rpy", line 134, in script
    init python:
  File "game/script.rpy", line 136, in <module>
    url = url +  "?genre_id=" + "&genre_id=".join(favorite_genres)
NameError: name 'favorite_genres' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\SSAFY\Desktop\renpy-8.2.1-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\SSAFY\Desktop\renpy-8.2.1-sdk\renpy\main.py", line 526, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 134, in script
    init python:
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 134, in script
    init python:
  File "C:\Users\SSAFY\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\SSAFY\Desktop\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 136, in <module>
    url = url +  "?genre_id=" + "&genre_id=".join(favorite_genres)
NameError: name 'favorite_genres' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
dongjin_love 1.0
Mon May 20 10:12:43 2024
